# Generated by Django 3.2 on 2021-05-14 14:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is Alist Store. The store with the best of the best products to offer.'),
        ),
    ]
